name: deploy-book

on:
  push:
    branches:
      - main

# Optional, falls du interne Links als /<repo>/ … ausliefern willst.
env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Entweder requirements.txt nutzen …
      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # … oder minimal nur jupyter-book installieren:
      - name: Install Jupyter Book
        run: pip install -U jupyter-book

      # Optional: Wenn du Sphinx-Extensions brauchst, hier ergänzen:
      # run: pip install jupyter-book sphinx-external-toc myst-parser

      - name: Build the book
        run: jupyter-book build MD_Praktikum_Anleitung

      # GitHub Pages v4 Workflow: zuerst konfigurieren
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: MD_Praktikum_Anleitung/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
